### ISSUE TITLE
Python bindings broken

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/NWXCMake#12]
This is a "manual" transfer of https://github.com/NWChemEx-Project/NWChemEx/issues/110. It's assumed that whomever works on this issue will be able to see the other one, even though it's private.

**Comment by zachcran** [comment]
> I think the problem is PUBLIC_HEADER is not set in CMaize anymore. Here is the https://github.com/CMakePP/CMaize/pull/90 that disabled it. @zachcran Is it possible to enable it back?

@keceli I think you are right. It is possible to set PUBLIC_HEADER in CMaize again. However, this option is related to Mac OSX Frameworks and is not supposed to be a general-use option in CMake from my understanding, so I am hesitant to enable it again when we don't support Mac OSX Framework structures currently. It flattens the include directory on install as well, or throws a large warning message if you do not set the PUBLIC_HEADER install destination, so it does not work well with NWChemEx repositories as they are currently laid out.

You can still retrieve the list of include files through CMaize with the code below, as long as you only plan to interface with **projects built with CMaize**. Otherwise, the `HEADER_SET` CMake target property seems like a reasonable place to look for a list of header files, so we could add the list of header files there. It seems to be the preferred way to list header files after it was introduced in CMake 3.23.

Let me know what you think and if you have other suggestions on how to handle this!

CMaize code:
```cmake
# Any time after the call to `cmaize_add_library()` defining your library

# Get the currently active CMaize project
cpp_get_global(cmaize_project CMAIZE_PROJECT)

# Get the desired CMaize target by name (in NWChemEx, this is usually the current project name, too)
CMaizeProject(get_target "${cmaize_project}" tgt ${PROJECT_NAME})

# Get the CMaize BuildTarget `includes` attribute, which is a list of include files for the target
BuildTarget(GET "${tgt}" include_file_list includes)

# Print the include file list to make sure everything worked
message(DEBUG "include_file_list: ${include_file_list}")
```

**Comment by ryanmrichard** [comment]
For reference [here](https://cmake.org/cmake/help/latest/prop_tgt/PUBLIC_HEADER.html) is the CMake documentation for `PUBLIC_HEADER`. I agree with Zach, we shouldn't have been setting it in the first place/that's not the appropriate place to be obtaining the include files from.

**Comment by keceli** [comment]
@zachcran no problem, getting the headers list through CMaize should work too.

**Comment by keceli** [comment]
@zachcran Any suggestions for retrieving header file list for the dependency targets, i.e. how do we extract the header files for ParallelZone while building PlugingPlay with CMaize? Looks like CMaize has `includes` attribute only for the main target.

**Comment by zachcran** [comment]
Hi @keceli, I don't know of a great way to get the header files for ParallelZone while building PluginPlay right now. The CMaize target objects are not retained in the installed `*Config.cmake` files, if ParallelZone was installed beforehand. If it is pulled in and built as part of the PluginPlay build, you should be able to retrieve the ParallelZone CMaize project and get the target from there. This isn't a great solution, though, since it doesn't work if ParallelZone was installed.

From what I understand, you shouldn't need to pull in ParallelZone's header files for PluginPlay's bindings though, and they are intended to be separated from each other. Are you able to get at what you need in ParallelZone by using `import parallelzone` in the Python in PluginPlay maybe?

**Comment by ryanmrichard** [comment]
As @zachcran alluded to, CMake is really designed to work recursively. By trying to have PluginPlay also directly worry about ParallelZone, you're essentially starting to unroll the recursive structure into a loop. While this is entirely possible to accomplish, you're fighting CMake's intrinsic design and it's going to be an uphill battle. 

Realistically what should happen is that ParallelZone generates its Python bindings, and packages them. In PluginPlay, you then look for those packaged bindings and use them. If you don't find the packaged bindings, you need to generate the packaged bindings, not roll them into PluginPlay's bindings. 

Put another way, think about how most Python packages are distributed. If a package depends on say Numpy, most Python packages are not going to copy/paste Numpy's source into their Python package, rather they're just going to do `import numpy`. The way this all used to work was more or less the copy/paste solution (which I think is the root of https://github.com/NWChemEx-Project/.github/issues/34).

**Comment by keceli** [comment]
I'll get back to the packaging issue, but right now I am confused about extracting the target with CMaize:

```
cpp_get_global(cmaize_project CMAIZE_PROJECT)
message(STATUS "cmaize_project: ${cmaize_project}")
# Get the desired CMaize target by name (in NWChemEx, this is usually the current project name, too)
CMaizeProject(get_target "${cmaize_project}" tgt ${PROJECT_NAME})
message(STATUS "PROJECT_NAME: ${PROJECT_NAME}")
message(STATUS "tgt: ${tgt}")
```
I insert these lines into ParallelZone and PluginPlay CMakeListsts.txt after `cmaize_add_library`. 

In ParallelZone, I get:
```
-- cmaize_project: cpp_0791i_1682433189
-- PROJECT_NAME: parallelzone
-- tgt: cpp_ez0me_1682433219
```
while in PluginPlay, I get:
```
-- cmaize_project: cpp_lmciw_1682433244
-- PROJECT_NAME: pluginplay
-- tgt:
```
My question is, why I cannot access the target in PluginPlay while I can in ParallelZone. I need the target to access the `includes` attribute.

**Comment by zachcran** [comment]
There might be a bug when CMaize is setting `CMAIZE_PROJECT`, so it doesn't change back to the PluginPlay CMaize project after the ParallelZone build. Can you add these lines after `cpp_get_global(cmaize_project CMAIZE_PROJECT)` and tell me what the output is?

```cmake
# after cpp_get_global(cmaize_project CMAIZE_PROJECT)
CMaizeProject(GET "${cmaize_project}" proj_name name)
message(STATUS "CMAIZE_PROJECT name: ${proj_name}")
```

As a potential workaround for now, you should be able to do `cpp_get_global(cmaize_project CMAIZE_PROJECT_${PROJECT_NAME})` to get a specific project.

**Comment by keceli** [comment]
Before ParallelZone build:
```
-- CMAIZE_PROJECT name: pluginplay
```
After:
```
-- CMAIZE_PROJECT name: parallelzone
```

**Comment by zachcran** [comment]
Thanks for looking into that. That definitely seems like a CMaize bug. The CMAIZE_PROJECT name after the ParallelZone build in Pluginplay should still be "pluginplay", not "parallelzone". For now, the best way to access the current CMaize project is to use `CMAIZE_PROJECT_${PROJECT_NAME}` mentioned in the workaround above.

**Comment by keceli** [comment]
Thanks @zachcran, the workaround fixes the problem.

**Comment by zachcran** [comment]
Awesome, thanks for your patience and willingness to try out a few things to get this working! Let me know if you see any other issues I can help with.

**Comment by twindus** [comment]
@keceli I want to make sure that we don't lose @ryanmrichard comment about CMake propagating recursively through the stack.  It seems that we are just doing a workaround on a problem that is going to come back to bite us.  So, can we fix this issue in a more sustainable manner.

**Comment by keceli** [comment]
@twindus Here, the aim is to get back to the working stage as before CPP->CMaize transition. I have created issue #17 to follow up with the packaging problem.
